In [1]:
import torch
torch.__version__
x = torch.empty(4,2) #4x2 빈 텐서 생성
print(x)
x = torch.rand(4,2)
print(x)
x = torch.zeros(4,2, dtype = torch.long)
print(x)
x = torch.tensor([3,2.3])
print(x)
x = x.new_ones(4,3,dtype = torch.double) #기존에 생성된 텐서의 속성을 그대로 물러 받아 1로 채워진 새로운 텐서를 만드는 함수: 기존텐서.new_ones(새로운크기)
print(x)


tensor([[-5.6736e+14,  1.7782e-42],
        [ 0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00]])
tensor([[0.6321, 0.3839],
        [0.7839, 0.0133],
        [0.4980, 0.1492],
        [0.0275, 0.7109]])
tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])
tensor([3.0000, 2.3000])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


### CUDA Tensors
   * .to() 메소드를 사용하여 텐서를 CPU나 GPU로 이동할 수 있음

In [8]:
x = torch.randn(1)
print(x)
print(x.item())
print(x.dtype)
print(type(x.item()))

dev = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(dev)
y = torch.ones_like(x, device=dev)
print(y)
x=x.to(dev) #
print(x)
z = x + y
print(z)
print(z.to('cpu', torch.double)) #torch.double은 torch.float64와 동일

tensor([-0.4205])
-0.42047223448753357
torch.float32
<class 'float'>
cpu
tensor([1.])
tensor([-0.4205])
tensor([0.5795])
tensor([0.5795], dtype=torch.float64)


### 다차원 텐서 표현
   * 0D Tensor(scalar)
      - 하나의 숫자를 담고 있는 텐서
      - 축과 형상(shape)이 없음
   * 1D Tensor(Vector)
      - 리스트와 유사한 형태의 텐서
      - 하나의 축이 존재

In [13]:
t0 = torch.tensor(0)
print(t0.ndim)
print(t0.shape)
print(t0)

0
torch.Size([])
tensor(0)


In [14]:
t1 = torch.tensor([1, 2, 3])
print(t1.ndim)
print(t1.shape)
print(t1)

1
torch.Size([3])
tensor([1, 2, 3])


   * 2D Tensor(Matrix)
     - 행렬과 같이 2개의 축이 존재함
     - 일반적인 수치나 통계 데이터 셋이 이에 해당됨
     - Samples(행 데이터)과 features(열 데이터)를 가진 구조로 사용
        + 하나의 샘플은 여러 featues를 가짐

In [15]:
t2 = torch.tensor([
    [1, 2, 3], 
    [4, 5, 6],
    [7, 8, 9]])
print(t2.ndim)
print(t2.shape)
print(t2)

2
torch.Size([3, 3])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


   * 3D Tensor(Cube)
      - 3개의 축이 존재함
      - 연속된 시퀀스 데이터나 시간 축이 포함된 시계열 데이터에 해당함
         + 주식 가격 데이터셋, 시간에 따른 질병 발병 데이터 등
         + 흑백 이미지
      - Samples, Timesteps, Features를 가진 구조임

In [18]:
t3 = torch.tensor([
    [[1, 2, 3], 
     [4, 5, 6],
     [7, 8, 9]],
    [[1, 2, 3], 
     [4, 5, 6],
     [7, 8, 9]],
    [[1, 2, 3], 
     [4, 5, 6],
     [7, 8, 9]]])
print(t3.ndim)
print(t3.shape)
print(t3)

3
torch.Size([3, 3, 3])
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


   * 4D Tensor
      - 4개의 축이 존재함
      - 컬러 이미지 데이터가 대표적인 사례
      - Samples, Height, Width, Channels를 가진 구조임

   ![4D Tensor](4d_tensor.png)

   * 5D Tensor
      - 5개의 축이 존재함
      - 비디오 데이터
      - Samples, Frames, Height, Width, Channels를 가진 구조임

### 텐서의 연산
   * 텐서에 대한 수학 연산, 삼각함수, 비트 연산, 비교 연산, 집계 등


In [25]:
import math
a = torch.rand(1, 2) * 2 - 1
print(a)
print(torch.abs(a))
print(torch.ceil(a))
print(torch.floor(a))
print(torch.clamp(a, -0.5, 0.5))
print(torch.min(a))
print(torch.max(a))
print(torch.mean(a))
print(torch.std(a))
print(torch.prod(a))
print(torch.unique(torch.tensor([1, 2, 3, 1, 3, 2, 4, 5, 5, 7])))

tensor([[-0.2177,  0.6000]])
tensor([[0.2177, 0.6000]])
tensor([[-0., 1.]])
tensor([[-1.,  0.]])
tensor([[-0.2177,  0.5000]])
tensor(-0.2177)
tensor(0.6000)
tensor(0.1911)
tensor(0.5782)
tensor(-0.1306)
tensor([1, 2, 3, 4, 5, 7])


In [30]:
print(a)
print(a.abs())
print(a.ceil())
print(a.floor())
print(a.clamp(-0.5, 0.5))
print(a.min())
print(a.max())
print(a.mean())
print(a.std())
print(a.prod())
print(torch.tensor([1, 2, 3, 1, 3, 2, 4, 5, 5, 7]).unique())

tensor([[-0.2177,  0.6000]])
tensor([[0.2177, 0.6000]])
tensor([[-0., 1.]])
tensor([[-1.,  0.]])
tensor([[-0.2177,  0.5000]])
tensor(-0.2177)
tensor(0.6000)
tensor(0.1911)
tensor(0.5782)
tensor(-0.1306)
tensor([1, 2, 3, 4, 5, 7])


### 텐서의 연산
   * min(), max() 함수는 dim 인자를 줄 경우 argmax와 argmin도 함께 리턴함
      + argmax: 최대값을 가진 인덱스
      + argmin: 최소값을 가진 인덱스

In [32]:
x = torch.rand(2, 2) # 2 x 2
print(x)
print(x.max(dim = 0)) #dim=0 -> column-wise
print(x.min(dim = 1)) #dim=1 -> row-wise

tensor([[0.5196, 0.0102],
        [0.0750, 0.4006]])
torch.return_types.max(
values=tensor([0.5196, 0.4006]),
indices=tensor([0, 1]))
torch.return_types.min(
values=tensor([0.0102, 0.0750]),
indices=tensor([1, 0]))


   * torch.add() 덧셈

In [37]:
x = torch.rand(2, 2) # 2 x 2 random number matrix
print(x)
y = torch.rand(2, 2)
print(y)

tensor([[0.2769, 0.3100],
        [0.3137, 0.7519]])
tensor([[0.3250, 0.9552],
        [0.5080, 0.0996]])


In [38]:
print(x + y)
print(torch.add(x, y))

tensor([[0.6019, 1.2652],
        [0.8216, 0.8514]])
tensor([[0.6019, 1.2652],
        [0.8216, 0.8514]])


In [41]:
result = torch.empty(2, 2)
torch.add(x, y, out = result)
print(result.shape)
print(result)

torch.Size([2, 2])
tensor([[0.6019, 1.2652],
        [0.8216, 0.8514]])


   * in-place 방식
      + 연산 결과를 텐서에 저장하여 기존값을 변경하는 연산의 이름 뒤에는 _가 붙음
      + x.add_(y): x + y의 결과를 x에 저장함

In [42]:
print(x)
print(y)
y.add_(x)
print(y)

tensor([[0.2769, 0.3100],
        [0.3137, 0.7519]])
tensor([[0.3250, 0.9552],
        [0.5080, 0.0996]])
tensor([[0.6019, 1.2652],
        [0.8216, 0.8514]])


In [43]:
print(x)
print(y)
print(x - y)
print(torch.sub(x, y))
print(x.sub(y))

tensor([[0.2769, 0.3100],
        [0.3137, 0.7519]])
tensor([[0.6019, 1.2652],
        [0.8216, 0.8514]])
tensor([[-0.3250, -0.9552],
        [-0.5080, -0.0996]])
tensor([[-0.3250, -0.9552],
        [-0.5080, -0.0996]])
tensor([[-0.3250, -0.9552],
        [-0.5080, -0.0996]])


In [44]:
print(x)
print(y)
print(x * y)
print(torch.mul(x, y))
print(x.mul(y))

tensor([[0.2769, 0.3100],
        [0.3137, 0.7519]])
tensor([[0.6019, 1.2652],
        [0.8216, 0.8514]])
tensor([[0.1666, 0.3923],
        [0.2577, 0.6401]])
tensor([[0.1666, 0.3923],
        [0.2577, 0.6401]])
tensor([[0.1666, 0.3923],
        [0.2577, 0.6401]])


In [49]:
print(x)
print(y)
print(x / y)
print(torch.div(x, y))
print(x.div(y))
print(y.div(x))

tensor([[0.2769, 0.3100],
        [0.3137, 0.7519]])
tensor([[0.6019, 1.2652],
        [0.8216, 0.8514]])
tensor([[0.4600, 0.2450],
        [0.3817, 0.8831]])
tensor([[0.4600, 0.2450],
        [0.3817, 0.8831]])
tensor([[0.4600, 0.2450],
        [0.3817, 0.8831]])
tensor([[2.1739, 4.0809],
        [2.6196, 1.1324]])


   * torch.mm 내적(dot product)

In [51]:
print(torch.mm(x, y))
print(torch.matmul(x, y))

tensor([[0.4214, 0.6143],
        [0.8065, 1.0370]])
tensor([[0.4214, 0.6143],
        [0.8065, 1.0370]])


In [54]:
a1 = torch.tensor([[1, 2], [3, 4]])
a2 = torch.tensor([[1, 0], [0, 1]])
b = torch.mm(a1, a2)
print(a1)
print(a2)
print(b)
print(a1 @ a2)

tensor([[1, 2],
        [3, 4]])
tensor([[1, 0],
        [0, 1]])
tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]])


### 텐서의 조작
   * indexing: Numpy처럼 인덱싱 형태로 사용 가능

In [59]:
x = torch.tensor([[1, 2], [3, 4]])
print(x)
print(x[0, 0]) #행과 열의 인덱스로 항목을 지정함
print(x[0, 1])
print(x[1, 0])
print(x[1, 1])

print(x[:, 0]) #slicing을 적용하여 행 또는 열을 지정
print(x[1, :])

tensor([[1, 2],
        [3, 4]])
tensor(1)
tensor(2)
tensor(3)
tensor(4)
tensor([1, 3])
tensor([3, 4])


   * 텐서의 size나 shape를 변경: view()
      + 기본적으로 변경 전과 후의 텐서 안 "원소 개수"가 유지되어야 함
      + -1로 설정되면 계산을 통해 해당 크기값을 유추해서 정함

In [65]:
x = torch.randn(4, 5)
print(x)
y = x.view(20) #원수를 20개 나열
print(y)
z = x.view(5, -1) #개수를 5로 지정, 나머지(열)는 알아서 계산해 줌
print(z)
z1 = x.view(-1, 5)
print(z1)

tensor([[ 1.6660,  1.9758,  1.0375,  0.7277, -0.4490],
        [ 0.2917,  0.1901, -1.3653,  0.1359, -0.5905],
        [ 0.3216,  2.0556,  0.4016, -0.4212,  1.0031],
        [ 0.4183, -0.3962, -0.1158,  0.1007, -0.1020]])
tensor([ 1.6660,  1.9758,  1.0375,  0.7277, -0.4490,  0.2917,  0.1901, -1.3653,
         0.1359, -0.5905,  0.3216,  2.0556,  0.4016, -0.4212,  1.0031,  0.4183,
        -0.3962, -0.1158,  0.1007, -0.1020])
tensor([[ 1.6660,  1.9758,  1.0375,  0.7277],
        [-0.4490,  0.2917,  0.1901, -1.3653],
        [ 0.1359, -0.5905,  0.3216,  2.0556],
        [ 0.4016, -0.4212,  1.0031,  0.4183],
        [-0.3962, -0.1158,  0.1007, -0.1020]])
tensor([[ 1.6660,  1.9758,  1.0375,  0.7277, -0.4490],
        [ 0.2917,  0.1901, -1.3653,  0.1359, -0.5905],
        [ 0.3216,  2.0556,  0.4016, -0.4212,  1.0031],
        [ 0.4183, -0.3962, -0.1158,  0.1007, -0.1020]])


   * 텐서에 값이 1개만 존재할 때 이를 숫자로 가져을 수 있음: item()

In [69]:
x = torch.randn(1)
print(x)
print(x.item())
print(x.dtype)

tensor([-0.6925])
-0.6925444602966309
torch.float32


   * 차원을 축소: squeeze()
       + 배치 차원 추가 목적
       + 브로드캐스팅 맞추기
       + 행과 열 벡터의 변환
       + 신경망 입력 차원 맞추기

In [75]:
t1 = torch.rand(1, 3, 3) # 1 x 3 x 3 텐서
print(t1)
print(t1.shape)
t2 = t1.squeeze()
print(t2)
print(t2.shape)
t3 = t2.squeeze()
print(t3)
print(t3.shape)

tensor([[[0.3433, 0.5558, 0.5251],
         [0.7230, 0.2226, 0.9644],
         [0.2668, 0.3889, 0.4681]]])
torch.Size([1, 3, 3])
tensor([[0.3433, 0.5558, 0.5251],
        [0.7230, 0.2226, 0.9644],
        [0.2668, 0.3889, 0.4681]])
torch.Size([3, 3])
tensor([[0.3433, 0.5558, 0.5251],
        [0.7230, 0.2226, 0.9644],
        [0.2668, 0.3889, 0.4681]])
torch.Size([3, 3])


   * 차원을 확장: unsqueeze()
       + 배치 차원 추가 목적
       + 브로드캐스팅 맞추기
       + 행과 열 벡터의 변환
       + 신경망 입력 차원 맞추기

In [78]:
print(t3.shape)
t4 = torch.unsqueeze(t3, dim = 2)
print(t4)
print(t4.shape)
t5 = t3.unsqueeze(0)
print(t5)
print(t5.shape)

torch.Size([3, 3])
tensor([[[0.3433],
         [0.5558],
         [0.5251]],

        [[0.7230],
         [0.2226],
         [0.9644]],

        [[0.2668],
         [0.3889],
         [0.4681]]])
torch.Size([3, 3, 1])
tensor([[[0.3433, 0.5558, 0.5251],
         [0.7230, 0.2226, 0.9644],
         [0.2668, 0.3889, 0.4681]]])
torch.Size([1, 3, 3])


   * 텐서간 결합: stack()

   * 텐서를 결합(concatenate)하는 메소드: cat()