# TensorFlow
  * 가장 널리 쓰이는 딥러닝 프레임워크 중의 하나임
  * 구글이 주도하여 개발함
  * 파이썬과 C++ API를 기본 제공하고  
    자바스크립트, 자바 등 다양한 프로그래밍 언어를 지원함
  * tf.keras를 중심으로 고수준의 API를 제공함
  * TPU(Tensor Processing Unit) 지원함
    +  TPU는 GPU보다 전력을 적게 소모하므로 경제적임
    +  32비트(float32) 곱셈연산을 16비트(float16)로 낮추어 수행

## Tensorflow architecture
  * [Layer-5] Tensorflow Estimators <- High-level, Object-Oriented API
  * [Layer-4] tf.layers, tf.losses, tf.metrics <- Reusable libraries for common model components
  * [Layer-3] Python Tensorflow <- Provides Ops, which wrap C++ kernels
  * [Layer-2] C++ Tensorflow
  * [Layer-1] CPU, GPU, TPU <- Kernels work on one or more platforms

### [Tensorflow 시작하기]
  * 기본 모듈 임포트
  * Tensorflow 버전 확인하기

In [2]:
import numpy as np
import tensorflow as tf

print(tf.__version__)

2.20.0


## Tensor 객체의 기본 개념
  * Type: string, float32, float16, int32, int8 등
  * Shape(차원): 0, 1, 2차원 등의 데이터 차원
  * Rank(축): 차원의 개수

### [Tensor의 차원과 연산]

In [13]:
a = tf.constant(2)
print(tf.rank(a))
print(a.shape)
print(a)

tf.Tensor(0, shape=(), dtype=int32)
()
tf.Tensor(2, shape=(), dtype=int32)


In [14]:
b=tf.constant([2, 3])
print(tf.rank(b))
print(b)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor([2 3], shape=(2,), dtype=int32)


In [15]:
c=tf.constant([[2, 3], [6, 7]])
print(tf.rank(c))
print(c)

tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(
[[2 3]
 [6 7]], shape=(2, 2), dtype=int32)


In [16]:
d=tf.constant(['Hello world!'])
#d=tf.constant('Hello world!')
print(tf.rank(d))
print(d)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor([b'Hello world!'], shape=(1,), dtype=string)


### [난수(Random number) 생성]

In [17]:
rand1=tf.random.uniform([1], 0, 1) #0 ~ 1사이의 균일 분포 난수 발생
print(rand.shape)
print(rand)

(1,)
tf.Tensor([0.279451], shape=(1,), dtype=float32)


In [18]:
rand2=tf.random.normal([1, 2], 0, 1) #평균이 0, 표준편차 1인 정규분포 난수 발생
print(rand2.shape)
print(rand2)

(1, 2)
tf.Tensor([[-0.60249996  1.1395795 ]], shape=(1, 2), dtype=float32)


In [19]:
rand3=tf.random.normal(shape=(3,2), mean=0, stddev=1)
print(rand3.shape)
print(rand3)

(3, 2)
tf.Tensor(
[[-0.40071458  0.5248656 ]
 [-0.2817742   0.9427031 ]
 [ 2.124239    1.1727471 ]], shape=(3, 2), dtype=float32)


### [즉시 실행 모드(Eager Mode) 지원]
  * Tensorflow를 Python에서처럼 바로 실행함
  * 1.x 버전에서는 '그래프'를 생성하고 초기화한 후에 세션을 통해 **값을 흐르게 하는 작업**을 진행해야 함

In [20]:
a=tf.constant(3)
b=tf.constant(2)
print(tf.add(a, b))
print(a+b)

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)


In [21]:
print(tf.subtract(a, b))
print(a-b)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)


In [22]:
print(tf.multiply(a, b))
print(a*b)

tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)


In [23]:
print(tf.divide(a, b))
print(a/b)

tf.Tensor(1.5, shape=(), dtype=float64)
tf.Tensor(1.5, shape=(), dtype=float64)


### [Tensorflow ↔ Numpy]
  * numpy()
  * tf.convert_to_tensor()

In [26]:
c=tf.add(a, b).numpy() #계산 결과를 numpy()로 변환함
print(type(c))

<class 'numpy.int32'>


In [27]:
c_square=np.square(c, dtype=np.float32)
c_tensor=tf.convert_to_tensor(c_square)
print(c_tensor)
print(type(c_tensor))

tf.Tensor(25.0, shape=(), dtype=float32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


### [Numpy처럼 사용하기]

In [29]:
t=tf.constant([[1.0, 2.0, 3.0],[4.0, 5.0, 6.0]])
print(t.shape)
print(t.dtype)

(2, 3)
<dtype: 'float32'>


In [39]:
print(t[:, 1:]) #Slicing

tf.Tensor(
[[2. 3.]
 [5. 6.]], shape=(2, 2), dtype=float32)


In [44]:
print(t)
t[..., 1, tf.newaxis] #...을 Ellipsis라고 하며, 이는 앞의 모든 차원을 유지하라는 의미. 마지막 차원에서 1번(인덱스)을 선택하고 그 자리에 새로운 축을 추가함(선택된 1열의 값은 새로운 행이 됨)

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)


<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[2.],
       [5.]], dtype=float32)>

In [45]:
t+10 #모든 요소에 10을 더하게 됨

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[11., 12., 13.],
       [14., 15., 16.]], dtype=float32)>

In [46]:
tf.square(t)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)>

In [47]:
t@tf.transpose(t) #@는 행렬의 곱

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

### [Type 변환]
   * Tensor의 기본 dtype
      - float형 Tensor: float32
      - int형 Tensor: int32
   * 연산 시 Tensor의 type이 반드시 일치해야 함
      - float32 ↔ float32
      - int32 ↔ int32
      - float32 ↔ int32 (x)
   * type 변환은 tf.cast()를 사용함

In [51]:
a=tf.constant(2)
print(a)
b=tf.constant(2.0)
print(b)
#c=a+b #type이 서로 맞지 않기 때문에 에러 발생
print("a_dtype:", type(a), "b_dtype:", type(b))
c=tf.cast(a, dtype=tf.float32)+b
print(c)

tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(2.0, shape=(), dtype=float32)
a_dtype: <class 'tensorflow.python.framework.ops.EagerTensor'> b_dtype: <class 'tensorflow.python.framework.ops.EagerTensor'>
tf.Tensor(4.0, shape=(), dtype=float32)


### [AutoGraph]
  * Tensorflow가 작업을 좀 더 빠르게 하기 위한 방법으로 Graph를 만들어 연산을 진행함
  * tf.Graph
  * 이를 사용하면 모바일 어플리케이션, 임베디드 기기, 백엔드 서버와 같이 Python 인터프리터가 없는 환경에서 Tensorflow를 사용할 수 있음
1텐서플로우 기초 29분 48초