## 넘파이 연습
#### (수치 계산과 데이터 처리의 기초)
* Pandas: 데이터 분석
* Numerical Python
* 고성능 과학 계산용 패키지로 강력한 N차원 배열 객체
* 다차원 컨테이너
* 정교한 브로드캐스팅 기능
* 파이썬 리스트와 유사하나 더 빠르고 메모리를 효율적으로 관리
* 반복문 없이 배열에 대한 처리 지원(빠름, 편리)
* 데이터 과학 도구의 핵심적 위치

In [1]:
import numpy as np
np.__version__


'2.4.6'

### 배열 생성
* 1차원
* 2차원
* 3차원

In [2]:
a1 = np.array([1,2,3,4,5,6,7,8,9,10])
a2 = np.array([[1,2,3],[4,5,6]])
a3 = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]], [[13,14,15], [16,17,18]], [[19,20,21], [22,23,24]]])
print(a1)
print(type(a1)) 
print(a1.shape)
print(a1[0], a1[1], a1[2], a1[3], a1[4])
print(a2)
print(type(a2))
print(a2.shape)
print(a2[0,0], a2[0,1], a2[0,2])
print(a3)
print(type(a3))
print(a3.shape)


[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>
(10,)
1 2 3 4 5
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)
1 2 3
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]]]
<class 'numpy.ndarray'>
(4, 2, 3)


* 셀을 마크다운으로 전환하는 단축키는 M
* 셀을 코드로 전환하는 단축키는 Y
* A는 바로 위에 셀을 만듦
* B는 바로 아래에 셀을 만듦
* Shift+Enter: 코드 실행 후 다음 셀로 이동
* Ctrl+Enter: 현재 셀의 코드 실행 후, 그대로 머뭄

In [3]:
import numpy as np
d2 = np.ndarray((2,3), dtype=int)
print(d2)
d3 = np.full((4,2), 5)
print(d3)
range_array = np.arange(10)
print(range_array)
rand_arr= np.random.rand(2,2)
print(rand_arr)



[[                  0                   0                   0]
 [                  0       2475403850928 5711979398116543675]]
[[5 5]
 [5 5]
 [5 5]
 [5 5]]
[0 1 2 3 4 5 6 7 8 9]
[[0.37550991 0.00097911]
 [0.86611121 0.47319684]]


In [4]:
print(np.arange(10000).reshape(100,100))
a= np.array([20,30,40,50])
b=np.arange(4)
c=a-b
print(c)
b**2
10*np.sin(a)
a<35


[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]
[20 29 38 47]


array([ True,  True, False, False])

In [5]:
A = np.array([[1,1],[0,1]])
B=np.array([[2,0],[3,4]])
print(A)
print(B)
print(A*B) # elementwise product
print(A@B) # matrix product
A.dot(B) # another matrix product
rg=np.random.default_rng(1) # random number generator
print(rg.standard_normal((2,3))) # 2x3 array of standard normally distributed random numbers
print(rg.random((3,4))) # 3x4 array of uniformly distributed random numbers between 0 and 1


[[1 1]
 [0 1]]
[[2 0]
 [3 4]]
[[2 0]
 [0 4]]
[[5 4]
 [3 4]]
[[ 0.34558419  0.82161814  0.33043708]
 [-1.30315723  0.90535587  0.44637457]]
[[0.82770259 0.40919914 0.54959369 0.02755911]
 [0.75351311 0.53814331 0.32973172 0.7884287 ]
 [0.30319483 0.45349789 0.1340417  0.40311299]]


In [6]:
def f(x,y):
    return 10*x+y

b = np.fromfunction(f, (5,4), dtype=int) # 5x4 array with values f(0,0), f(0,1), ..., f(4,3)
print(b)

print(b.shape)
print(b[:,2]) # all rows, column 2
for i in b.flat:
    #print(i)
    pass

a = np.floor(10*rg.random((3,4)))
print(a)

print(a.ravel()) # flatten the array

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]
(5, 4)
[ 2 12 22 32 42]
[[2. 2. 7. 2.]
 [4. 9. 9. 7.]
 [5. 2. 1. 9.]]
[2. 2. 7. 2. 4. 9. 9. 7. 5. 2. 1. 9.]


In [7]:
import numpy as np
a = np.arange(100)
a.ravel() # 다차원 배열을 1차원으로 평평하게 해줌
#print(a)
print(a.shape)
b=a.reshape(5, 20); print(a.shape); print(b.shape) 

(100,)
(100,)
(5, 20)


In [8]:
a1 = np.array([1, 2, 3, 4, 5])
print(a1)
a2 = np.array([(1.5, 2, 3), (4,5,6)])
print(a2)
a3 = np.array([((1,2,3), (4,5,6)), ((7,8,9), (10,11,12))])
print(a3)
c1 = np.array([[1+2j, 2+3j], [3+4j, 4+5j]])
print(c1)
print(c1.dtype)
print(c1.real)  
print(c1.imag)
print("conjugate output", c1.conjugate()) # 공액 복소수 출력
e1 = np.empty((3, 4), dtype=int) #empty() 함수는 지정된 형태와 데이터 타입을 가지는 새로운 배열을 생성하지만, 배열의 요소들은 초기화되지 않은 상태로 남아 있습니다. 즉, 배열의 요소들은 메모리에서 이전에 사용된 값이 그대로 남아 있을 수 있습니다. 따라서 empty() 함수를 사용할 때는 배열의 요소들을 반드시 초기화하거나, 이후에 값을 할당하여 사용해야 합니다. 예를 들어, e1 = np.empty((3, 4))는 3행 4열의 빈 배열을 생성하지만, 이 배열의 요소들은 초기화되지 않은 상태로 남아 있을 수 있습니다.
print(e1)

l1 = np.linspace(0, 10, 5) #linspace() 함수는 지정된 범위 내에서 균일한 간격으로 숫자를 생성하는 데 사용됩니다. 여기서는 0부터 10까지의 범위에서 5개의 숫자를 생성합니다. 반환되는 배열은 [0., 2.5, 5., 7.5, 10.]이 됩니다. linspace() 함수는 시작점과 끝점을 포함하여 지정된 개수만큼의 숫자를 생성하기 때문에, 간격이 균일하게 분포된 숫자들을 얻을 수 있습니다.
print(l1)
print(l1.dtype)



[1 2 3 4 5]
[[1.5 2.  3. ]
 [4.  5.  6. ]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[1.+2.j 2.+3.j]
 [3.+4.j 4.+5.j]]
complex128
[[1. 2.]
 [3. 4.]]
[[2. 3.]
 [4. 5.]]
conjugate output [[1.-2.j 2.-3.j]
 [3.-4.j 4.-5.j]]
[[4611686018427387904 4611686018427387904 4619567317775286272
  4611686018427387904]
 [4616189618054758400 4621256167635550208 4621256167635550208
  4619567317775286272]
 [4617315517961601024 4611686018427387904 4607182418800017408
  4621256167635550208]]
[ 0.   2.5  5.   7.5 10. ]
float64


In [9]:
import numpy as np
import matplotlib.pyplot as plt

a = np.arange(15).reshape(3, -1)
print(a.shape)
print(a.dtype)
print(a.ndim)
print(a.itemsize)
print(a.size)
print(a.nbytes)
print(a)

(3, 5)
int64
2
8
15
120
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [10]:
rg = np.random.default_rng(1)
b = rg.random((2,3))
