In [4]:
import numpy as np
import matplotlib.pyplot as plt

a = np.arange(15).reshape(3, 5)
print(a.shape)
print(a.dtype)
print(a.ndim)
print(a.itemsize)
print(a.size)
print(a.nbytes)

(3, 5)
int64
2
8
15
120


In [ ]:
a1 = np.array([1, 2, 3, 4, 5])
print(a1)
a2 = np.array([(1.5, 2, 3), (4,5,6)])
print(a2)
a3 = np.array([((1,2,3), (4,5,6)), ((7,8,9), (10,11,12))])
print(a3)
c1 = np.array([[1+2j, 2+3j], [3+4j, 4+5j]])
print(c1)
print(c1.dtype)
print(c1.real)  
print(c1.imag)
print(c1.conjugate())
e1 = np.empty((3, 4), dtype=int) #empty() 함수는 지정된 형태와 데이터 타입을 가지는 새로운 배열을 생성하지만, 배열의 요소들은 초기화되지 않은 상태로 남아 있습니다. 즉, 배열의 요소들은 메모리에서 이전에 사용된 값이 그대로 남아 있을 수 있습니다. 따라서 empty() 함수를 사용할 때는 배열의 요소들을 반드시 초기화하거나, 이후에 값을 할당하여 사용해야 합니다. 예를 들어, e1 = np.empty((3, 4))는 3행 4열의 빈 배열을 생성하지만, 이 배열의 요소들은 초기화되지 않은 상태로 남아 있을 수 있습니다.
print(e1)

l1 = np.linspace(0, 10, 5) #linspace() 함수는 지정된 범위 내에서 균일한 간격으로 숫자를 생성하는 데 사용됩니다. 여기서는 0부터 10까지의 범위에서 5개의 숫자를 생성합니다. 반환되는 배열은 [0., 2.5, 5., 7.5, 10.]이 됩니다. linspace() 함수는 시작점과 끝점을 포함하여 지정된 개수만큼의 숫자를 생성하기 때문에, 간격이 균일하게 분포된 숫자들을 얻을 수 있습니다.
print(l1)
print(l1.dtype)



[1 2 3 4 5]
[[1.5 2.  3. ]
 [4.  5.  6. ]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[1.+2.j 2.+3.j]
 [3.+4.j 4.+5.j]]
complex128
[[1. 2.]
 [3. 4.]]
[[2. 3.]
 [4. 5.]]
[[1.-2.j 2.-3.j]
 [3.-4.j 4.-5.j]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 0.   2.5  5.   7.5 10. ]
float64


In [5]:
import numpy as np
a = np.arange(100)
a.ravel()
print(a.shape)
b=a.reshape(5, 20); print(a.shape); print(b.shape)

(100,)
(100,)
(5, 20)
